spring:

  application:
    name: druzhba-hub-app

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${HOST_LOCAL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    mongodb:
      authentication-database: admin
      database: druzhba-hub
      port: 27017
      host: ${HOST_LOCAL}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
email:
  confirm:
    link: http://${HOST_LOCAL}:8080/api/register/confirm?token=

logging:
  file:
    path: logs
    name: ${logging.file.path}/druzhba-hub-logs.log
  level:
    root: INFO

gcp:
  bucket-name:
    ${GCS_BUCKET_NAME}
  project-id:
    ${GCS_PROJECT_ID}
  credentials:
    file-path:
      ${GCS_CREDENTIALS_PATH}
jwt:
  secret: ${JWT_SECRET}
  expiration: 10