spring:

  application:
    name: druzhba-hub-app

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${HOST_LOCAL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
